[package]
name = "aoc_2015"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
md-5 = "0.10.5"
regex = "1"

[dev-dependencies]
test-case = "2.2"
